# Generated by Django 4.1.7 on 2023-03-12 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("year_of_birth", models.IntegerField(default="0")),
                ("address", models.CharField(default="0", max_length=500)),
                ("gender", models.CharField(default="0", max_length=100)),
                ("phone", models.IntegerField(default="0")),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="0", max_length=200, unique=True)),
                ("year", models.IntegerField(default="0", null=True)),
                (
                    "owner_name",
                    models.CharField(default="0", max_length=200, null=True),
                ),
                ("format", models.CharField(default="0", max_length=200, null=True)),
                ("city", models.CharField(default="0", max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("description", models.CharField(default="", max_length=500)),
                ("author", models.CharField(default="", max_length=500)),
                ("review", models.CharField(default="", max_length=500)),
                ("stars", models.IntegerField(default="0")),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lab1.publisher"
                    ),
                ),
            ],
        ),
    ]
