USE dbmsLab3
GO

--update confl

INSERT INTO Student VALUES(22, 'Alex', 100)
ALTER DATABASE dbmsLab3 SET ALLOW_SNAPSHOT_ISOLATION ON

WAITFOR DELAY '00:00:05'
BEGIN TRAN
UPDATE Student SET nameS = 'New Alex 1' WHERE id = 22
WAITFOR DELAY '00:00:05'
COMMIT TRAN

-- ALTER DATABASE dbmsLab3 SET ALLOW_SNAPSHOT_ISOLATION OFF
-- UPDATE Student SET nameS = 'NewName' WHERE ID = 22
-- SELECT * FROM Student
