# Generated by Django 4.1.7 on 2023-03-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab1", "0002_remove_books_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="review",
            field=models.CharField(default="", max_length=500),
        ),
    ]
