# Generated by Django 4.1.7 on 2023-03-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="review",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AddField(
            model_name="books",
            name="stars",
            field=models.IntegerField(default="0"),
        ),
    ]
