# Generated by Django 4.1.7 on 2023-03-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab1", "0005_alter_books_publisher_customersbooks"),
    ]

    operations = [
        migrations.AddField(
            model_name="customersbooks",
            name="amount",
            field=models.IntegerField(default="0"),
        ),
    ]
