# Generated by Django 4.1.7 on 2023-03-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab1", "0006_customersbooks_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publisher",
            old_name="city",
            new_name="country",
        ),
    ]
