# Generated by Django 4.1.7 on 2023-03-20 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab1", "0008_rename_name_customers_name_of_customer"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CustomersBooks",
            new_name="BookSold",
        ),
    ]
