# Generated by Django 4.1.7 on 2023-03-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lab1", "0003_books_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publisher",
            old_name="name",
            new_name="publisher",
        ),
    ]
