# Generated by Django 4.1.7 on 2023-04-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab1", "0009_rename_customersbooks_booksold"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publisher",
            name="country",
            field=models.CharField(default="0", max_length=200),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="format",
            field=models.CharField(default="0", max_length=200),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="owner_name",
            field=models.CharField(default="0", max_length=200),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="publisher",
            field=models.CharField(default="0", max_length=200),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="year",
            field=models.IntegerField(default="0"),
        ),
    ]
